### PR TITLE
Update gemoji to 4.2

### PR DESCRIPTION
**Pull request by dozoisch**

### CODE REVIEW

**Comment by dozoisch** [comment]
I'll try to see why the test fail. Seems to be due to 2 characters emoji.

I'm trying to figure out a way I could have them be parsed properly.

**Comment by dozoisch** [comment]
@wooorm so it seems like the issue is not the test itself but the modifier. 

Here are some examples of what is parsed:

```
{ type: 'SymbolNode',
  value: '🏌',
  position:
   Position {
     start: { line: 1, column: 45, offset: 44 },
     end: { line: 1, column: 47, offset: 46 } } }
{ type: 'WordNode',
  children: [ { type: 'TextNode', value: '️\uFEOF', position: [Object] } ],
  position:
   Position {
     start: { line: 1, column: 47, offset: 46 },
     end: { line: 1, column: 48, offset: 47 } } }
{ type: 'SymbolNode',
  value: '\u200D',
  position:
   Position {
     start: { line: 1, column: 48, offset: 47 },
     end: { line: 1, column: 49, offset: 48 } } }
{ type: 'SymbolNode',
  value: '♀',
  position:
   Position {
     start: { line: 1, column: 49, offset: 48 },
     end: { line: 1, column: 50, offset: 49 } } }
```

```
{ type: 'SymbolNode',
  value: '🤹',
  position:
   Position {
     start: { line: 1, column: 45, offset: 44 },
     end: { line: 1, column: 47, offset: 46 } } }
{ type: 'SymbolNode',
  value: '\u200D',
  position:
   Position {
     start: { line: 1, column: 47, offset: 46 },
     end: { line: 1, column: 48, offset: 47 } } }
{ type: 'SymbolNode',
  value: '♂',
  position:
   Position {
     start: { line: 1, column: 48, offset: 47 },
     end: { line: 1, column: 49, offset: 48 } } }
```

I'm trying to figure out how to modify the `modifier` to support these multi-codepoints emoji.

After modifier, the first element (with the base emoji) gets marked as `EmoticonNode` (so it seems like it gets in here https://github.com/syntax-tree/nlcst-emoji-modifier/blob/cd7b372ea2c6a7527c8ce0da446e27c5844c94fc/index.js#L87-L88 properly). It just doesn't aggregate the subsequent chars. 

For the first version it seems like it should test that the node + next word node + all the next SymbolNode ares a valid emoji. 

For the second it needs to check for emoji + all the next SymbolNodes.

**Comment by wooorm** [comment]
@dozoisch Hey! 👋 

Thanks for working on this, that’s super awesome!

What you’re proposing seems like the right fix! Can you write the code for that too?

Cheers,
Titus

**Comment by dozoisch** [comment]
Alright, I'll try to put up something!

**Comment by wooorm** [comment]
Awesome! Thanks @dozoisch!

**Comment by dozoisch** [comment]
@wooorm Alright, did a first pass today. I covered these two cases (which fixed 85/104 failing) and discovered a third case. Hopefully by end of tomorrow I'll have something up!

**Comment by wooorm** [comment]
Sweet! Thanks for still working on this! 👏👏👏

**Comment by dozoisch** [comment]
@wooorm I had used const/let instead of vars earlier. Want me to update the whole file to use const/let? Otherwise I will hoist my vars to the top.

**Comment by wooorm** [comment]
Just merged! I hoisted the vars now so you don’t have to deal with the code-style.

It looks great btw, thanks so much!

**Comment by dozoisch** [comment]
@wooorm thanks :)! 

If you can cut a release with the update, I'll send a pr to update retext-emoji to use the latest version of this package (and gemoji 4.2 at the same time).

**Comment by wooorm** [comment]
Sweet! I was just updating some of the other ancient parts first.

**Comment by dozoisch** [comment]
@wooorm awesome, thanks for your work

**Comment by wooorm** [comment]
Thank you a bunch! I appreciate the work you put into this!

I need to get to work now; if you have some time to whip up a PR I’d appreciate it too, but otherwise I’ll work on that later today!

**Comment by dozoisch** [comment]
@wooorm it's nighttime here, but I can get it done by tonight (in like 18 hours)

**Comment by dozoisch** [comment]
@wooorm thanks for cutting 5.0 :) updated my project and everything works so far!

**Comment by wooorm** [comment]
Good! Thanks again for working on this :)

**Pull request closed without merging**
